// AUTO-GENERATED by scripts/compute_anchors.py — do not hand-edit.
// Measured directly from each asset's own pixel data: real painted-content
// bounding box, ground-contact footprint, mean tone, and opaque coverage.
// `contain()`-in-a-fixed-box only knows a file's full W/H, which is why
// idols float (padding varies per file) and some pandals swallow the whole
// scene (coverage varies per file). This is what placement should use instead.

export interface AutoAnchors {
  content: { x: number; y: number; w: number; h: number }
  foot: { cx: number; w: number }
  tone: { L: number; s: number }
  coverage: number
  naturalW: number
  naturalH: number
}

export interface WorldTone {
  tone: { L: number; s: number }
  naturalW: number
  naturalH: number
}

export const DURGA_ANCHORS: Record<string, AutoAnchors> = {
  "contemporary": {
    "content": {
      "x": 0.0225,
      "y": 0.0137,
      "w": 0.955,
      "h": 0.9772
    },
    "foot": {
      "cx": 0.4851,
      "w": 0.6824
    },
    "tone": {
      "L": 95.1,
      "s": 0.321
    },
    "coverage": 0.502,
    "naturalW": 666,
    "naturalH": 1098
  },
  "ekchala": {
    "content": {
      "x": 0.0196,
      "y": 0.0233,
      "w": 0.9608,
      "h": 0.9534
    },
    "foot": {
      "cx": 0.5054,
      "w": 0.8381
    },
    "tone": {
      "L": 131.8,
      "s": 0.548
    },
    "coverage": 0.731,
    "naturalW": 765,
    "naturalH": 644
  },
  "fierce": {
    "content": {
      "x": 0.0703,
      "y": 0.0392,
      "w": 0.8385,
      "h": 0.8379
    },
    "foot": {
      "cx": 0.2523,
      "w": 0.16
    },
    "tone": {
      "L": 111.0,
      "s": 0.339
    },
    "coverage": 0.365,
    "naturalW": 768,
    "naturalH": 1376
  },
  "monumental": {
    "content": {
      "x": 0.0,
      "y": 0.0022,
      "w": 0.9766,
      "h": 0.9978
    },
    "foot": {
      "cx": 0.5093,
      "w": 0.6147
    },
    "tone": {
      "L": 106.7,
      "s": 0.44
    },
    "coverage": 0.407,
    "naturalW": 768,
    "naturalH": 1376
  },
  "royal-gold": {
    "content": {
      "x": 0.0587,
      "y": 0.1248,
      "w": 0.9167,
      "h": 0.7296
    },
    "foot": {
      "cx": 0.5156,
      "w": 0.3264
    },
    "tone": {
      "L": 138.1,
      "s": 0.484
    },
    "coverage": 0.55,
    "naturalW": 732,
    "naturalH": 1298
  },
  "sabeki": {
    "content": {
      "x": 0.0534,
      "y": 0.1475,
      "w": 0.9154,
      "h": 0.7253
    },
    "foot": {
      "cx": 0.5349,
      "w": 0.6472
    },
    "tone": {
      "L": 137.7,
      "s": 0.384
    },
    "coverage": 0.506,
    "naturalW": 768,
    "naturalH": 1376
  },
  "sculptural": {
    "content": {
      "x": 0.0855,
      "y": 0.0618,
      "w": 0.8855,
      "h": 0.8045
    },
    "foot": {
      "cx": 0.3544,
      "w": 0.4174
    },
    "tone": {
      "L": 158.5,
      "s": 0.096
    },
    "coverage": 0.468,
    "naturalW": 725,
    "naturalH": 1279
  },
  "serene": {
    "content": {
      "x": 0.0454,
      "y": 0.0093,
      "w": 0.9413,
      "h": 0.9815
    },
    "foot": {
      "cx": 0.4638,
      "w": 0.7844
    },
    "tone": {
      "L": 165.8,
      "s": 0.23
    },
    "coverage": 0.457,
    "naturalW": 749,
    "naturalH": 1081
  },
  "shiuli-durga": {
    "content": {
      "x": 0.003,
      "y": 0.1478,
      "w": 0.9954,
      "h": 0.6631
    },
    "foot": {
      "cx": 0.4921,
      "w": 0.16
    },
    "tone": {
      "L": 177.9,
      "s": 0.251
    },
    "coverage": 0.463,
    "naturalW": 658,
    "naturalH": 1211
  },
  "terracotta-idol": {
    "content": {
      "x": 0.0826,
      "y": 0.1659,
      "w": 0.9034,
      "h": 0.7242
    },
    "foot": {
      "cx": 0.4752,
      "w": 0.7287
    },
    "tone": {
      "L": 117.3,
      "s": 0.593
    },
    "coverage": 0.555,
    "naturalW": 714,
    "naturalH": 1338
  },
  "village": {
    "content": {
      "x": 0.0199,
      "y": 0.0217,
      "w": 0.9601,
      "h": 0.955
    },
    "foot": {
      "cx": 0.5007,
      "w": 0.9197
    },
    "tone": {
      "L": 134.3,
      "s": 0.488
    },
    "coverage": 0.547,
    "naturalW": 752,
    "naturalH": 644
  },
  "white-minimal": {
    "content": {
      "x": 0.1015,
      "y": 0.2063,
      "w": 0.82,
      "h": 0.602
    },
    "foot": {
      "cx": 0.5107,
      "w": 0.1815
    },
    "tone": {
      "L": 216.1,
      "s": 0.062
    },
    "coverage": 0.305,
    "naturalW": 739,
    "naturalH": 1367
  }
}

export const PANDAL_ANCHORS: Record<string, AutoAnchors> = {
  "bamboo": {
    "content": {
      "x": 0.0091,
      "y": 0.0168,
      "w": 0.9831,
      "h": 0.9665
    },
    "foot": {
      "cx": 0.4957,
      "w": 0.16
    },
    "tone": {
      "L": 145.3,
      "s": 0.267
    },
    "coverage": 0.519,
    "naturalW": 768,
    "naturalH": 895
  },
  "bengali-temple": {
    "content": {
      "x": 0.0208,
      "y": 0.0118,
      "w": 0.9584,
      "h": 0.9765
    },
    "foot": {
      "cx": 0.4993,
      "w": 1.0
    },
    "tone": {
      "L": 151.1,
      "s": 0.345
    },
    "coverage": 0.635,
    "naturalW": 722,
    "naturalH": 1276
  },
  "floral-structure": {
    "content": {
      "x": 0.0202,
      "y": 0.0173,
      "w": 0.9595,
      "h": 0.9654
    },
    "foot": {
      "cx": 0.5035,
      "w": 0.16
    },
    "tone": {
      "L": 176.6,
      "s": 0.329
    },
    "coverage": 0.598,
    "naturalW": 741,
    "naturalH": 867
  },
  "geometric": {
    "content": {
      "x": 0.0251,
      "y": 0.0118,
      "w": 0.9498,
      "h": 0.9763
    },
    "foot": {
      "cx": 0.2421,
      "w": 0.2887
    },
    "tone": {
      "L": 136.5,
      "s": 0.253
    },
    "coverage": 0.559,
    "naturalW": 598,
    "naturalH": 1266
  },
  "minimal": {
    "content": {
      "x": 0.0242,
      "y": 0.0182,
      "w": 0.9515,
      "h": 0.9635
    },
    "foot": {
      "cx": 0.5119,
      "w": 0.9745
    },
    "tone": {
      "L": 194.4,
      "s": 0.081
    },
    "coverage": 0.459,
    "naturalW": 619,
    "naturalH": 823
  },
  "monastery": {
    "content": {
      "x": 0.0228,
      "y": 0.0178,
      "w": 0.9543,
      "h": 0.9643
    },
    "foot": {
      "cx": 0.5072,
      "w": 0.7225
    },
    "tone": {
      "L": 149.0,
      "s": 0.371
    },
    "coverage": 0.652,
    "naturalW": 657,
    "naturalH": 841
  },
  "royal-palace": {
    "content": {
      "x": 0.0204,
      "y": 0.0207,
      "w": 0.9593,
      "h": 0.9641
    },
    "foot": {
      "cx": 0.4936,
      "w": 0.4342
    },
    "tone": {
      "L": 171.7,
      "s": 0.326
    },
    "coverage": 0.723,
    "naturalW": 737,
    "naturalH": 724
  },
  "ruins": {
    "content": {
      "x": 0.0201,
      "y": 0.0195,
      "w": 0.9597,
      "h": 0.9611
    },
    "foot": {
      "cx": 0.1811,
      "w": 0.3636
    },
    "tone": {
      "L": 100.1,
      "s": 0.219
    },
    "coverage": 0.622,
    "naturalW": 745,
    "naturalH": 771
  },
  "terracotta": {
    "content": {
      "x": 0.0196,
      "y": 0.0128,
      "w": 0.9607,
      "h": 0.9744
    },
    "foot": {
      "cx": 0.4993,
      "w": 1.0
    },
    "tone": {
      "L": 89.4,
      "s": 0.594
    },
    "coverage": 0.861,
    "naturalW": 764,
    "naturalH": 1172
  },
  "toran": {
    "content": {
      "x": 0.0217,
      "y": 0.0135,
      "w": 0.9566,
      "h": 0.973
    },
    "foot": {
      "cx": 0.8918,
      "w": 0.2148
    },
    "tone": {
      "L": 139.1,
      "s": 0.637
    },
    "coverage": 0.503,
    "naturalW": 691,
    "naturalH": 1113
  },
  "wooden": {
    "content": {
      "x": 0.0203,
      "y": 0.0163,
      "w": 0.9593,
      "h": 0.9675
    },
    "foot": {
      "cx": 0.4944,
      "w": 0.846
    },
    "tone": {
      "L": 144.8,
      "s": 0.264
    },
    "coverage": 0.693,
    "naturalW": 738,
    "naturalH": 922
  },
  "zamindar-mansion": {
    "content": {
      "x": 0.0213,
      "y": 0.0161,
      "w": 0.9574,
      "h": 0.9679
    },
    "foot": {
      "cx": 0.5104,
      "w": 0.9363
    },
    "tone": {
      "L": 147.8,
      "s": 0.312
    },
    "coverage": 0.675,
    "naturalW": 705,
    "naturalH": 934
  }
}

export const WORLD_TONE: Record<string, WorldTone> = {
  "forest": {
    "tone": {
      "L": 60.5,
      "s": 0.575
    },
    "naturalW": 768,
    "naturalH": 1376
  },
  "ganga-ghat": {
    "tone": {
      "L": 185.6,
      "s": 0.242
    },
    "naturalW": 768,
    "naturalH": 1376
  },
  "himalaya": {
    "tone": {
      "L": 213.3,
      "s": 0.084
    },
    "naturalW": 768,
    "naturalH": 1376
  },
  "howrah": {
    "tone": {
      "L": 125.0,
      "s": 0.263
    },
    "naturalW": 688,
    "naturalH": 1281
  },
  "kolkata-street": {
    "tone": {
      "L": 117.7,
      "s": 0.479
    },
    "naturalW": 768,
    "naturalH": 1376
  },
  "misty-valley": {
    "tone": {
      "L": 169.9,
      "s": 0.132
    },
    "naturalW": 768,
    "naturalH": 1376
  },
  "rainy-kolkata": {
    "tone": {
      "L": 93.0,
      "s": 0.369
    },
    "naturalW": 768,
    "naturalH": 1376
  },
  "rooftop": {
    "tone": {
      "L": 65.4,
      "s": 0.316
    },
    "naturalW": 728,
    "naturalH": 1318
  },
  "sea": {
    "tone": {
      "L": 228.2,
      "s": 0.101
    },
    "naturalW": 768,
    "naturalH": 1376
  },
  "tea-garden": {
    "tone": {
      "L": 161.7,
      "s": 0.214
    },
    "naturalW": 728,
    "naturalH": 1341
  },
  "terrace-lights": {
    "tone": {
      "L": 203.0,
      "s": 0.24
    },
    "naturalW": 768,
    "naturalH": 948
  },
  "village": {
    "tone": {
      "L": 153.2,
      "s": 0.442
    },
    "naturalW": 768,
    "naturalH": 1376
  },
  "zamindar": {
    "tone": {
      "L": 118.7,
      "s": 0.467
    },
    "naturalW": 768,
    "naturalH": 1376
  }
}
